#TODO 2024 samples have variable number of files (30-70), accounting for a total of 10^6 events
#TODO N.B. 2018 had 100 files accounting for 10^5 events -> training would run over the first 20 files (i.e. 20% of sample)
#TODO    setting initial training on first 5 files (N.B. this may correspond to up 7-16% of the total sample, which is still a lot of events)
#TODO Only ctau = {0.1, 1.0, 10, 100} exist for ScenarioB1 in the 2024 production (other ctau from the old V1p3 set are not available)

# [0]
bparkProductionAll_2024--scenarioB1_mpi_1_mA_0p33_ctau_0p1: &bparkProductionAll_2024--scenarioB1_mpi_1_mA_0p33_ctau_0p1
  path:  'root://gfe02.grid.hep.ph.ic.ac.uk/pnfs/hep.ph.ic.ac.uk/data/cms/store/user/tafoyava/samples/bParking/2024/GluGluHToDarkShowers-ScenarioB1_Par-ctau-0p1-mA-0p33-mpi-1_TuneCP5_13p6TeV_powheg-pythia8'
  #files: 'nano_[0-5].root'
  files: 'nano_[0-15].root' 
  xs:   1.0 # [pb]
  model_param:
    mpi:    1.0
    mA:     0.33
    ctau:   0.1
  force_xs: true
  isMC:     true
  maxevents_scale: 1.0

# [1]
bparkProductionAll_2024--scenarioB1_mpi_1_mA_0p33_ctau_1p0: &bparkProductionAll_2024--scenarioB1_mpi_1_mA_0p33_ctau_1p0
  path:  'root://gfe02.grid.hep.ph.ic.ac.uk/pnfs/hep.ph.ic.ac.uk/data/cms/store/user/tafoyava/samples/bParking/2024/GluGluHToDarkShowers-ScenarioB1_Par-ctau-1p0-mA-0p33-mpi-1_TuneCP5_13p6TeV_powheg-pythia8'
  #files: 'nano_[0-5].root'
  files: 'nano_[0-15].root' 
  xs:   1.0 # [pb]
  model_param:
    mpi:    1.0
    mA:     0.33
    ctau:   1.0
  force_xs: true
  isMC:     true
  maxevents_scale: 1.0

# [2]
bparkProductionAll_2024--scenarioB1_mpi_1_mA_0p33_ctau_10: &bparkProductionAll_2024--scenarioB1_mpi_1_mA_0p33_ctau_10
  path:  'root://gfe02.grid.hep.ph.ic.ac.uk/pnfs/hep.ph.ic.ac.uk/data/cms/store/user/tafoyava/samples/bParking/2024/GluGluHToDarkShowers-ScenarioB1_Par-ctau-10-mA-0p33-mpi-1_TuneCP5_13p6TeV_powheg-pythia8'
  #files: 'nano_[0-5].root'
  files: 'nano_[0-17].root' 
  xs:   1.0 # [pb]
  model_param:
    mpi:    1.0
    mA:     0.33
    ctau:   10.0
  force_xs: true
  isMC:     true
  maxevents_scale: 1.0

# [3]
bparkProductionAll_2024--scenarioB1_mpi_1_mA_0p33_ctau_100: &bparkProductionAll_2024--scenarioB1_mpi_1_mA_0p33_ctau_100
  path:  'root://gfe02.grid.hep.ph.ic.ac.uk/pnfs/hep.ph.ic.ac.uk/data/cms/store/user/tafoyava/samples/bParking/2024/GluGluHToDarkShowers-ScenarioB1_Par-ctau-100-mA-0p33-mpi-1_TuneCP5_13p6TeV_powheg-pythia8'
  #files: 'nano_[0-5].root'
  files: 'nano_[0-24].root' 
  xs:   1.0 # [pb]
  model_param:
    mpi:    1.0
    mA:     0.33
    ctau:   100.0
  force_xs: true
  isMC:     true
  maxevents_scale: 1.0

# [4]
bparkProductionAll_2024--scenarioB1_mpi_2_mA_0p67_ctau_0p1: &bparkProductionAll_2024--scenarioB1_mpi_2_mA_0p67_ctau_0p1
  path:  'root://gfe02.grid.hep.ph.ic.ac.uk/pnfs/hep.ph.ic.ac.uk/data/cms/store/user/tafoyava/samples/bParking/2024/GluGluHToDarkShowers-ScenarioB1_Par-ctau-0p1-mA-0p67-mpi-2_TuneCP5_13p6TeV_powheg-pythia8'
  #files: 'nano_[0-5].root'
  files: 'nano_[0-24].root' 
  xs:   1.0 # [pb]
  model_param:
    mpi:    2.0
    mA:     0.67
    ctau:   0.1
  force_xs: true
  isMC:     true
  maxevents_scale: 1.0

# [5]
bparkProductionAll_2024--scenarioB1_mpi_2_mA_0p67_ctau_1p0: &bparkProductionAll_2024--scenarioB1_mpi_2_mA_0p67_ctau_1p0
  path:  'root://gfe02.grid.hep.ph.ic.ac.uk/pnfs/hep.ph.ic.ac.uk/data/cms/store/user/tafoyava/samples/bParking/2024/GluGluHToDarkShowers-ScenarioB1_Par-ctau-1p0-mA-0p67-mpi-2_TuneCP5_13p6TeV_powheg-pythia8'
  #files: 'nano_[0-5].root'
  files: 'nano_[0-25].root' 
  xs:   1.0 # [pb]
  model_param:
    mpi:    2.0
    mA:     0.67
    ctau:   1.0
  force_xs: true
  isMC:     true
  maxevents_scale: 1.0

# [6]
bparkProductionAll_2024--scenarioB1_mpi_2_mA_0p67_ctau_10: &bparkProductionAll_2024--scenarioB1_mpi_2_mA_0p67_ctau_10
  path:  'root://gfe02.grid.hep.ph.ic.ac.uk/pnfs/hep.ph.ic.ac.uk/data/cms/store/user/tafoyava/samples/bParking/2024/GluGluHToDarkShowers-ScenarioB1_Par-ctau-10-mA-0p67-mpi-2_TuneCP5_13p6TeV_powheg-pythia8'
  #files: 'nano_[0-5].root'
  files: 'nano_[0-18].root' 
  xs:   1.0 # [pb]
  model_param:
    mpi:    2.0
    mA:     0.67
    ctau:   10.0
  force_xs: true
  isMC:     true
  maxevents_scale: 1.0

# [7]
bparkProductionAll_2024--scenarioB1_mpi_2_mA_0p67_ctau_100: &bparkProductionAll_2024--scenarioB1_mpi_2_mA_0p67_ctau_100
  path:  'root://gfe02.grid.hep.ph.ic.ac.uk/pnfs/hep.ph.ic.ac.uk/data/cms/store/user/tafoyava/samples/bParking/2024/GluGluHToDarkShowers-ScenarioB1_Par-ctau-100-mA-0p67-mpi-2_TuneCP5_13p6TeV_powheg-pythia8'
  #files: 'nano_[0-5].root'
  files: 'nano_[0-34].root' 
  xs:   1.0 # [pb]
  model_param:
    mpi:    2.0
    mA:     0.67
    ctau:   100.0
  force_xs: true
  isMC:     true
  maxevents_scale: 1.0

# [8]
bparkProductionAll_2024--scenarioB1_mpi_2_mA_0p40_ctau_0p1: &bparkProductionAll_2024--scenarioB1_mpi_2_mA_0p40_ctau_0p1
  path:  'root://gfe02.grid.hep.ph.ic.ac.uk/pnfs/hep.ph.ic.ac.uk/data/cms/store/user/tafoyava/samples/bParking/2024/GluGluHToDarkShowers-ScenarioB1_Par-ctau-0p1-mA-0p40-mpi-2_TuneCP5_13p6TeV_powheg-pythia8'
  #files: 'nano_[0-5].root'
  files: 'nano_[0-20].root' 
  xs:   1.0 # [pb]
  model_param:
    mpi:    2.0
    mA:     0.4
    ctau:   0.1
  force_xs: true
  isMC:     true
  maxevents_scale: 1.0

# [9]
bparkProductionAll_2024--scenarioB1_mpi_2_mA_0p40_ctau_1p0: &bparkProductionAll_2024--scenarioB1_mpi_2_mA_0p40_ctau_1p0
  path:  'root://gfe02.grid.hep.ph.ic.ac.uk/pnfs/hep.ph.ic.ac.uk/data/cms/store/user/tafoyava/samples/bParking/2024/GluGluHToDarkShowers-ScenarioB1_Par-ctau-1p0-mA-0p40-mpi-2_TuneCP5_13p6TeV_powheg-pythia8'
  #files: 'nano_[0-5].root'
  files: 'nano_[0-21].root' 
  xs:   1.0 # [pb]
  model_param:
    mpi:    2.0
    mA:     0.4
    ctau:   1.0
  force_xs: true
  isMC:     true
  maxevents_scale: 1.0

# [10]
bparkProductionAll_2024--scenarioB1_mpi_2_mA_0p40_ctau_10: &bparkProductionAll_2024--scenarioB1_mpi_2_mA_0p40_ctau_10
  path:  'root://gfe02.grid.hep.ph.ic.ac.uk/pnfs/hep.ph.ic.ac.uk/data/cms/store/user/tafoyava/samples/bParking/2024/GluGluHToDarkShowers-ScenarioB1_Par-ctau-10-mA-0p40-mpi-2_TuneCP5_13p6TeV_powheg-pythia8'
  #files: 'nano_[0-5].root'
  files: 'nano_[0-19].root' 
  xs:   1.0 # [pb]
  model_param:
    mpi:    2.0
    mA:     0.4
    ctau:   10.0
  force_xs: true
  isMC:     true
  maxevents_scale: 1.0

# [11]
bparkProductionAll_2024--scenarioB1_mpi_2_mA_0p40_ctau_100: &bparkProductionAll_2024--scenarioB1_mpi_2_mA_0p40_ctau_100
  path:  'root://gfe02.grid.hep.ph.ic.ac.uk/pnfs/hep.ph.ic.ac.uk/data/cms/store/user/tafoyava/samples/bParking/2024/GluGluHToDarkShowers-ScenarioB1_Par-ctau-100-mA-0p40-mpi-2_TuneCP5_13p6TeV_powheg-pythia8'
  #files: 'nano_[0-5].root'
  files: 'nano_[0-17].root' 
  xs:   1.0 # [pb]
  model_param:
    mpi:    2.0
    mA:     0.4
    ctau:   100.0
  force_xs: true
  isMC:     true
  maxevents_scale: 1.0

# [12]
bparkProductionAll_2024--scenarioB1_mpi_4_mA_1p33_ctau_0p1: &bparkProductionAll_2024--scenarioB1_mpi_4_mA_1p33_ctau_0p1
  path:  'root://gfe02.grid.hep.ph.ic.ac.uk/pnfs/hep.ph.ic.ac.uk/data/cms/store/user/tafoyava/samples/bParking/2024/GluGluHToDarkShowers-ScenarioB1_Par-ctau-0p1-mA-1p33-mpi-4_TuneCP5_13p6TeV_powheg-pythia8'
  #files: 'nano_[0-5].root'
  files: 'nano_[0-20].root' 
  xs:   1.0 # [pb]
  model_param:
    mpi:    4.0
    mA:     1.33
    ctau:   0.1
  force_xs: true
  isMC:     true
  maxevents_scale: 1.0

# [13]
bparkProductionAll_2024--scenarioB1_mpi_4_mA_1p33_ctau_1p0: &bparkProductionAll_2024--scenarioB1_mpi_4_mA_1p33_ctau_1p0
  path:  'root://gfe02.grid.hep.ph.ic.ac.uk/pnfs/hep.ph.ic.ac.uk/data/cms/store/user/tafoyava/samples/bParking/2024/GluGluHToDarkShowers-ScenarioB1_Par-ctau-1p0-mA-1p33-mpi-4_TuneCP5_13p6TeV_powheg-pythia8'
  #files: 'nano_[0-5].root'
  files: 'nano_[0-16].root' 
  xs:   1.0 # [pb]
  model_param:
    mpi:    4.0
    mA:     1.33
    ctau:   1.0
  force_xs: true
  isMC:     true
  maxevents_scale: 1.0

# [14]
bparkProductionAll_2024--scenarioB1_mpi_4_mA_1p33_ctau_10: &bparkProductionAll_2024--scenarioB1_mpi_4_mA_1p33_ctau_10
  path:  'root://gfe02.grid.hep.ph.ic.ac.uk/pnfs/hep.ph.ic.ac.uk/data/cms/store/user/tafoyava/samples/bParking/2024/GluGluHToDarkShowers-ScenarioB1_Par-ctau-10-mA-1p33-mpi-4_TuneCP5_13p6TeV_powheg-pythia8'
  #files: 'nano_[0-5].root'
  files: 'nano_[0-24].root' 
  xs:   1.0 # [pb]
  model_param:
    mpi:    4.0
    mA:     1.33
    ctau:   10.0
  force_xs: true
  isMC:     true
  maxevents_scale: 1.0

# [15]
bparkProductionAll_2024--scenarioB1_mpi_4_mA_1p33_ctau_100: &bparkProductionAll_2024--scenarioB1_mpi_4_mA_1p33_ctau_100
  path:  'root://gfe02.grid.hep.ph.ic.ac.uk/pnfs/hep.ph.ic.ac.uk/data/cms/store/user/tafoyava/samples/bParking/2024/GluGluHToDarkShowers-ScenarioB1_Par-ctau-100-mA-1p33-mpi-4_TuneCP5_13p6TeV_powheg-pythia8'
  #files: 'nano_[0-5].root'
  files: 'nano_[0-14].root' 
  xs:   1.0 # [pb]
  model_param:
    mpi:    4.0
    mA:     1.33
    ctau:   100.0
  force_xs: true
  isMC:     true
  maxevents_scale: 1.0
